import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting TaskForge AI database seed...');

  // Clean existing tables in reverse dependency order
  await prisma.notification.deleteMany();
  await prisma.dispute.deleteMany();
  await prisma.review.deleteMany();
  await prisma.payout.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.submission.deleteMany();
  await prisma.application.deleteMany();
  await prisma.microTask.deleteMany();
  await prisma.project.deleteMany();
  await prisma.user.deleteMany();

  // Create Users
  const company1 = await prisma.user.create({
    data: {
      clerkId: 'user_company_acme',
      email: 'alex@acmelabs.com',
      name: 'Alex Vance',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      role: 'COMPANY',
      bio: 'Head of Product at Acme Labs. Building next-gen web applications.',
      subscriptionTier: 'PRO',
    },
  });

  const company2 = await prisma.user.create({
    data: {
      clerkId: 'user_company_nexus',
      email: 'sarah@nexus.io',
      name: 'Sarah Chen',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
      role: 'COMPANY',
      bio: 'Founder at Nexus Commerce. Scaling AI-first platforms.',
      subscriptionTier: 'FREE',
    },
  });

  const freelancer1 = await prisma.user.create({
    data: {
      clerkId: 'user_freelancer_rahul',
      email: 'rahul.dev@gmail.com',
      name: 'Rahul Sharma',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      role: 'FREELANCER',
      bio: 'Full-stack React & Next.js developer. UI/UX enthusiast & open-source contributor.',
      githubUrl: 'https://github.com/rahul-dev',
      portfolioUrl: 'https://rahul.dev',
      skills: JSON.stringify(['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Node.js', 'Prisma']),
      stripeAccountId: 'acct_1MockFreelancerRahul',
      stripeConnected: true,
    },
  });

  const freelancer2 = await prisma.user.create({
    data: {
      clerkId: 'user_freelancer_priya',
      email: 'priya.ai@gmail.com',
      name: 'Priya Patel',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      role: 'FREELANCER',
      bio: 'AI Systems engineer & Python specialist. LLM fine-tuning & API integrations.',
      githubUrl: 'https://github.com/priya-patel',
      skills: JSON.stringify(['Python', 'Gemini API', 'OpenAI', 'FastAPI', 'PostgreSQL', 'Stripe']),
      stripeAccountId: 'acct_1MockFreelancerPriya',
      stripeConnected: true,
    },
  });

  const adminUser = await prisma.user.create({
    data: {
      clerkId: 'user_admin_taskforge',
      email: 'admin@taskforge.ai',
      name: 'TaskForge Moderator',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      role: 'ADMIN',
      bio: 'TaskForge AI Operations & Dispute Resolution Team.',
    },
  });

  console.log('✅ Created initial Users');

  // Create Project 1: Food Delivery SaaS
  const project1 = await prisma.project.create({
    data: {
      companyId: company1.id,
      title: 'Build Food Delivery SaaS Platform',
      description: 'A complete end-to-end food ordering platform with real-time order tracking, menu selection, and admin dashboard.',
      totalBudget: 10000,
      currency: 'INR',
      deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), // 14 days from now
      status: 'FUNDED',
      stripePaymentIntentId: 'pi_mock_food_delivery_10000',
    },
  });

  // Funding Payment Record
  await prisma.payment.create({
    data: {
      projectId: project1.id,
      amount: 10000,
      currency: 'INR',
      status: 'SUCCEEDED',
      stripeSessionId: 'cs_test_mock_food_delivery_10000',
      stripePaymentIntentId: 'pi_mock_food_delivery_10000',
    },
  });

  // MicroTasks for Project 1 (Generated by AI)
  const task1 = await prisma.microTask.create({
    data: {
      projectId: project1.id,
      title: 'Design Food Delivery Landing Page',
      description: 'Create a high-converting, responsive landing page using Next.js 15, Tailwind CSS, and Framer Motion hero animations.',
      budget: 2000,
      currency: 'INR',
      deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
      skillsRequired: JSON.stringify(['Next.js', 'Tailwind CSS', 'Framer Motion', 'UI/UX']),
      status: 'COMPLETED',
      assignedToId: freelancer1.id,
    },
  });

  const task2 = await prisma.microTask.create({
    data: {
      projectId: project1.id,
      title: 'Create Auth System & User Roles',
      description: 'Integrate Clerk authentication supporting Customer, Restaurant Owner, and Delivery Agent roles with role middleware.',
      budget: 3000,
      currency: 'INR',
      deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
      skillsRequired: JSON.stringify(['React', 'Clerk', 'TypeScript', 'Next.js']),
      status: 'IN_REVIEW',
      assignedToId: freelancer1.id,
    },
  });

  const task3 = await prisma.microTask.create({
    data: {
      projectId: project1.id,
      title: 'Build Admin Dashboard & Menu Management',
      description: 'Develop an interactive dashboard to add/edit food items, manage inventory, view live orders, and export revenue reports.',
      budget: 5000,
      currency: 'INR',
      deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
      skillsRequired: JSON.stringify(['React', 'Prisma', 'PostgreSQL', 'Recharts']),
      status: 'OPEN',
    },
  });

  // Create Project 2: AI Support Bot Integration
  const project2 = await prisma.project.create({
    data: {
      companyId: company2.id,
      title: 'Customer Support AI Agent with Gemini API',
      description: 'Integrate Gemini AI model to answer customer queries automatically using knowledge base embedding search.',
      totalBudget: 15000,
      currency: 'INR',
      deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
      status: 'FUNDED',
      stripePaymentIntentId: 'pi_mock_support_bot_15000',
    },
  });

  const task4 = await prisma.microTask.create({
    data: {
      projectId: project2.id,
      title: 'Gemini RAG Pipeline & Prompt Engineering',
      description: 'Implement document parsing, vector indexing, and Gemini 1.5 prompt pipeline to return structured FAQ answers.',
      budget: 7500,
      currency: 'INR',
      deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
      skillsRequired: JSON.stringify(['Python', 'Gemini API', 'Vector DB', 'FastAPI']),
      status: 'ASSIGNED',
      assignedToId: freelancer2.id,
    },
  });

  const task5 = await prisma.microTask.create({
    data: {
      projectId: project2.id,
      title: 'Embeddable Chat Widget UI Component',
      description: 'Build a lightweight, customizable floating React chat widget with markdown rendering and streaming responses.',
      budget: 7500,
      currency: 'INR',
      deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
      skillsRequired: JSON.stringify(['React', 'TypeScript', 'Tailwind CSS', 'WebSockets']),
      status: 'OPEN',
    },
  });

  console.log('✅ Created Projects & MicroTasks');

  // Submissions for Completed & In-Review tasks
  const sub1 = await prisma.submission.create({
    data: {
      taskId: task1.id,
      freelancerId: freelancer1.id,
      deliverableUrl: 'https://foodie-landing-demo.vercel.app',
      repoUrl: 'https://github.com/rahul-dev/foodie-landing',
      notes: 'Completed full high-converting landing page responsive on all break points. Checked Lighthouse score (98).',
      qualityScore: 94,
      qualityReport: JSON.stringify({
        completeness: 98,
        codeQuality: 92,
        documentation: 90,
        requirementsMatch: 96,
        summary: 'Excellent implementation with modern Tailwind glassmorphism and clean Next.js 15 App router structure.',
      }),
      fraudScore: 2,
      fraudReport: JSON.stringify({
        isDuplicate: false,
        isSpam: false,
        aiGeneratedRisk: 'LOW',
        verdict: 'LEGITIMATE',
      }),
      status: 'APPROVED',
    },
  });

  // Payout for Task 1 (Approved & Transferred)
  await prisma.payout.create({
    data: {
      taskId: task1.id,
      freelancerId: freelancer1.id,
      amount: 2000,
      currency: 'INR',
      status: 'PAID',
      stripeTransferId: 'tr_mock_payout_2000_rahul',
    },
  });

  // Review for Task 1
  await prisma.review.create({
    data: {
      taskId: task1.id,
      reviewerId: company1.id,
      rating: 5,
      comment: 'Outstanding speed and visual quality! AI score accurately predicted how clean the code was.',
    },
  });

  // Submission for Task 2 (In Review)
  await prisma.submission.create({
    data: {
      taskId: task2.id,
      freelancerId: freelancer1.id,
      deliverableUrl: 'https://github.com/rahul-dev/foodie-auth-module',
      repoUrl: 'https://github.com/rahul-dev/foodie-auth-module',
      notes: 'Implemented Clerk Webhooks & custom Role guards for Next.js App Router.',
      qualityScore: 88,
      qualityReport: JSON.stringify({
        completeness: 90,
        codeQuality: 88,
        documentation: 85,
        requirementsMatch: 89,
        summary: 'Solid auth architecture with proper Zod validation.',
      }),
      fraudScore: 5,
      fraudReport: JSON.stringify({
        isDuplicate: false,
        isSpam: false,
        aiGeneratedRisk: 'LOW',
        verdict: 'LEGITIMATE',
      }),
      status: 'AI_VERIFIED',
    },
  });

  // Sample Notifications
  await prisma.notification.createMany({
    data: [
      {
        userId: freelancer1.id,
        title: 'Payout Released! 💰',
        message: '₹2,000 has been transferred to your connected Stripe account for "Design Food Delivery Landing Page".',
        type: 'SUCCESS',
      },
      {
        userId: company1.id,
        title: 'New AI Verified Submission',
        message: 'Rahul submitted Task 2 (Auth System). AI Verification Quality Score: 88/100.',
        type: 'ACTION',
      },
    ],
  });

  console.log('✅ Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
